# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1.xci
# IP: The module: 'sistema_lab2_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1.xci
# IP: The module: 'sistema_lab2_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
