# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0.xci
# IP: The module: 'sistema_lab2_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0.xci
# IP: The module: 'sistema_lab2_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/lab2/sintesis/lab2.srcs/sources_1/bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_lab2_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
