# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sistema_lab2/sistema_lab2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2 || ORIG_REF_NAME==sistema_lab2} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_processing_system7_0_0/sistema_lab2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_processing_system7_0_0 || ORIG_REF_NAME==sistema_lab2_processing_system7_0_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_0/sistema_lab2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_axi_gpio_0_0 || ORIG_REF_NAME==sistema_lab2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_ps7_0_axi_periph_0/sistema_lab2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_ps7_0_axi_periph_0 || ORIG_REF_NAME==sistema_lab2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_rst_ps7_0_100M_0/sistema_lab2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_rst_ps7_0_100M_0 || ORIG_REF_NAME==sistema_lab2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_xbar_0/sistema_lab2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_xbar_0 || ORIG_REF_NAME==sistema_lab2_xbar_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_1/sistema_lab2_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_axi_gpio_0_1 || ORIG_REF_NAME==sistema_lab2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_vio_0_0/sistema_lab2_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_vio_0_0 || ORIG_REF_NAME==sistema_lab2_vio_0_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_clk_wiz_0/sistema_lab2_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_clk_wiz_0 || ORIG_REF_NAME==sistema_lab2_clk_wiz_0} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_axi_gpio_0_2/sistema_lab2_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_axi_gpio_0_2 || ORIG_REF_NAME==sistema_lab2_axi_gpio_0_2} -quiet] -quiet

# IP: bd/sistema_lab2/ip/sistema_lab2_auto_pc_0/sistema_lab2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sistema_lab2_auto_pc_0 || ORIG_REF_NAME==sistema_lab2_auto_pc_0} -quiet] -quiet

# XDC: bd/sistema_lab2/sistema_lab2_ooc.xdc
