# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1.xci
# IP: The module: 'sistema_clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1.xci
# IP: The module: 'sistema_clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Facultad/MyS/UART_cont/sistesis/contador_configurable_UART.srcs/sources_1/bd/sistema/ip/sistema_clk_wiz_1/sistema_clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
